### ISSUE TITLE
Include a requirements.txt file with the required Python modules

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/emc-notebooks#1]
It is very common to include a `requirements.txt` file that contains the Python modules required by a software package, making it very convenient to install them using:

```console
pip install -r requirements.txt
``` 

As descried: https://learnpython.com/blog/python-requirements-file/

From INSTALL.txt:
```
    - Python module(s) needed:
        . xarray
        . netCDF4
        . numpy
        . scipy
        . cartopy
        . matplotlib
        . jupyterlab
        . nodejs
        . ipywidgets
        . ipyfilechooser
        . request
```

**Comment by manoch-iris** [comment]
The issue addressed in r0.5
