### ISSUE TITLE
INSTALL.txt is over scoped and could be a subsection

### ISSUE THREAD

**Issue by chad-earthscope** [iris-edu/emc-notebooks#2]
The included `INSTALL.txt` has some issues and I believe should simply be a section of the README.

A DESCRIPTION is included, but this is redundant with the README and has nothing to do with installing.

The first requirement is JupyterLab or the ("classic") Notebook, but in fact that is not needed at all and the `jupyterlab` module covers this. We can mention there are other options for Juypter at the end of the list of requirements, but as a novice user that had me unnecessarily confused.

**Comment by manoch-iris** [comment]
The issue addressed in r0.5
